# Generated by Django 5.2.8 on 2025-11-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando autorizão'), ('EM_VISITA', 'Em visita'), ('FINALIZADO', 'Visita finalzada')], default='AGUARDANDO', max_length=10, verbose_name='Status'),
        ),
    ]
